### ISSUE TITLE
Personal functional weights Computing 

### ISSUE THREAD

**Issue by mayizan** [gusevlab/fusion_twas#10]
Hi developers!
I am trying to run the Rscript to compute my own gene weight. I have made the preparation (the PATH, Plink bfile or R etc), but how could i generate right format of the $TMP file from my gene data?  There was little information on the Fusion Official site. Kindly, could developers give some suggestions ?
Rscript FUSION.compute_weights.R \
--bfile $INP \
**--tmp $TMP \**
--out $OUT \
--models top1,blup,bslmm,lasso,enet

**Comment by sashagusev** [comment]
Hi, the tmp file just needs to point to a writeable file that won't conflict with the other inputs. We usually do $TMP.tmp for example

**Comment by mayizan** [comment]
so the gene expression data should be merged in the Plink files? 
I think i made a big mistake! Thanks Mr. Gusev

**Comment by sashagusev** [comment]
Yes, sorry this wasn't clear, the plink/bfile inputs should contain the genotypes for the cis locus of a gene and the phenotype column should contain expression values for that gene

**Comment by mayizan** [comment]
Hi Gusev, Thanks for the kind suggestion in weight computation.
Now I am going to start associate test, but I wonder the sense of CHISQ and Z in the "PGC2.SCZ.sumstats" example file. I referred to the related algorithm such as "ImpG" and "FIZI" and the paper in 2014, but still get confused. Is there any relation between CHISQ value and Z?  also as LD_score and Z?

**Comment by sashagusev** [comment]
Hi, the chisq value is just the square of the test statistic, it is not used for the TWAS analysis. We just recommend using the LDSC pipeline munge_stats script to clean and process your GWAS data prior to analyzing it with FUSION.

**Comment by mayizan** [comment]
Hi Mr. Gusev, I have finished association and the temporary results really met my expectations. Thanks a lot for the kind support! I viewed the process again an I still have some questions for estimation and association. Was the estimation accomplished in weights computation process? 
If so, did the phenotype in the PLINK bfile contain missing value? The weight.R script was used to estimate missing value and perform cross-validation. The association.R script used the LDREF and GWAS summary from the panel used for estimation and for association.  (estimation was finished in weight.R)
If not, 100 samples (for example) with expression value was merged in PLINK bfile to perform estimation in weight.R. And the GWAS summary contained much more SNPs from different panels 2000 samples (for example) were used to perform prediction and association. (estimation was finished in association.R)
#Because I used RNA-sequencing for variation calling, there was no missing express value for each sample. So that I come up with this question.

**Comment by sashagusev** [comment]
Hi Mayizan, I don't understand the question, could you restate please?

**Comment by mayizan** [comment]
Hi Sasha, thanks a lot for the reply! Maybe i have got the sense from the webpage of your lab, the 'FUSION.compute_weights.R' script could compute the missing express value based on the existed express data. I think this script could compute gene express of 100 individuals based on the express data from 20 (for example) individuals among this group. Does that make sense? Did i underastand it correctly? Thanks agian for the answers!

**Comment by sashagusev** [comment]
Yes, this is correct. The compute_weights script estimates the gene expression weights for individuals you have measured which can then be used to predict for those without measured expression.
