### ISSUE TITLE
GCTA could not converge

### ISSUE THREAD

**Issue by xtmgah** [gusevlab/fusion_twas#11]
Hello

We previously used fusion for our RNA-seq data for TWAS analysis and it work pretty well. However, we want to extend the TWAS analysis to EWAS analysis by using replacing EPIC array (450k) data. We tried to calculate the functional weight for each probe based on the normalized beta value (0-1). However, we fund it's alway skipped the calculation due to the following error: 
"test_cg19923810 does not exist, likely GCTA could not converge, skipping gene". 

Then we did some analysis and found we found there is aways a error during the gcta program: 

gcta_nr_robust --grm test_cg19923810 --pheno test_cg19923810.pheno --qcovar mQTL_methylation.combined_covariates.txt --out test_cg19923810 --reml --reml-no-constrain --reml-lrt 1 
*******************************************************************
* Genome-wide Complex Trait Analysis (GCTA)
* version 1.21
* (C) 2010 Jian Yang, Hong Lee, Michael Goddard and Peter Visscher
* The University of Queensland
*******************************************************************
Analysis started: Mon Jun  3 13:44:11 2019

Options:
--grm test_cg19923810
--pheno test_cg19923810.pheno
--qcovar mQTL_methylation.combined_covariates.txt
--out test_cg19923810
--reml
--reml-no-constrain
--reml-lrt 1 

Note: This is a multi-thread program. You could specify the number of threads by the --thread-num option to speed up the computation if there are multiple processors in your machine.

Reading IDs of the GRM from [test_cg19923810.grm.id].
108 IDs read from [test_cg19923810.grm.id].
Reading the GRM from [test_cg19923810.grm.bin].
Reading the number of SNPs for the GRM from [test_cg19923810.grm.N.bin].
Pairwise genetic relationships between 108 individuals are included from [test_cg19923810.grm.bin].
Reading phenotypes from [test_cg19923810.pheno].
Nonmissing phenotypes of 108 individuals are included from [test_cg19923810.pheno].
Reading quantative covariates from [mQTL_methylation.combined_covariates.txt].
18 quantative covarites of 109 individuals read from [mQTL_methylation.combined_covariates.txt].

18 quantitative variable(s) included as covariate(s).
108 individuals are in common in these files.

Performing  REML analysis ... (Note: may take hours depending on sample size).
108 observations, 19 fixed effect(s), and 2 variance component(s)(including residual variance).
Calculating prior values of variance components by EM-REML ...

**Error: the X^t * V^-1 * X matrix is not invertible. Please check the covariate(s) and/or the environmental factor(s).**

Analysis finished: Mon Jun  3 13:44:11 2019
Computational time: 0:0:0

I attached this example data and see if you can help us to figure out why? Thanks so much and looking forward to your reply. 
[test.tar.gz](https://github.com/gusevlab/fusion_twas/files/3248802/test.tar.gz)

**Comment by sashagusev** [comment]
Hi, lack of REML convergence is a complicated issue that depends on the scale and complexity of the data. If you are seeing this consistently across phenotypes it likely means your sample size is insufficient to build predictors. I would recommend removing some of the fixed effects, homogenizing the data or removing outliers, or increasing the sample size. You can also try specifying the heritability to some small value using the --hsq_set flag in FUSION which will force the predictors to be built. However, typically poor performance of the heritability step will imply poor performance of the predictor. Hope that helps!
