### ISSUE TITLE
Code for checking that the model inputs are valid for the compute weights step

### ISSUE THREAD

**Issue by lcolladotor** [gusevlab/fusion_twas#12]
Hi,

Adding the following code after https://github.com/gusevlab/fusion_twas/blob/master/FUSION.compute_weights.R#L54 would be useful for making sure that the user specified correct model options.

```R
stopifnot(all(models %in% c('blup', 'lasso', 'top1', 'enet', 'bslmm')))
```

I just realized that in a TWAS run I specified `blump` instead of `blup` and no errors were reported because of this.

Best,
Leo

**Comment by sashagusev** [comment]
Thanks, it took some time but I've added a warning for this :)

**Comment by lcolladotor** [comment]
No worries, thanks Sasha!
