### ISSUE TITLE
Explicit control of the number of threads used

### ISSUE THREAD

**Issue by lcolladotor** [gusevlab/fusion_twas#16]
Hi,

I typically use `fusion_twas` on a compute cluster managed by [Son of Grid Engine](https://arc.liv.ac.uk/trac/SGE) (SGE), and thus need to be careful about the amount of resources I request such as memory and the number of threads per job. The `FUSION.compute_weights.R` script [here](https://github.com/gusevlab/fusion_twas/blob/master/FUSION.compute_weights.R) has several dependencies that can use more than 1 thread. However, currently there's no way to set them in the `FUSION.compute_weights.R` script.

## Threads use in dependencies

Here's what I've found about the threads in the dependencies:

* `glmnet`: I see that `glmnet::cv.glmnet()` has the argument `parallel` set to FALSE by default. Could leave as is to keep it simple.
* `plink`: you can specify the number of threads using the `--threads` option which I manually set in January to use 1 thread https://github.com/LieberInstitute/fusion_twas/commit/f677aaff715c62653fb2e05da97386b9a936480b#diff-a62928a27aae00e040d6f53f1ed7f256 in our fork of the fusion_twas repository. More information at https://www.cog-genomics.org/plink/1.9/other#threads. Note that there is a known limitation of `--threads` which you get a warning for (using `verbose=2`) when running the `lasso` model at https://github.com/gusevlab/fusion_twas/blob/master/FUSION.compute_weights.R#L84 if you set `--threads 1`. Since it's an OpenBLAS threads option, setting the environment variable `OPT_NUM_THREADS` could resolve this.
* `gcta` version 1.21 https://github.com/gusevlab/fusion_twas/blob/master/FUSION.compute_weights.R#L217-L219 which I see is quite outdated from looking at https://cnsgenomics.com/software/gcta/#Overview. From the changelog history, I can see that `--thread-num` existed prior to version 1.21 though I'm not sure how it gets the defaults https://cnsgenomics.com/software/gcta/#Download. As of version 1.91.4 it uses the environment variable `OMP_NUM_THREADS` to detect the number of threads if the option `--threads` is not specified https://cnsgenomics.com/software/gcta/#Multi-threadcomputing. From https://cnsgenomics.com/software/gcta/pre_gcta/ I downloaded the source for version 1.21 https://cnsgenomics.com/software/gcta/pre_gcta/gcta_1.21_src.zip and I see at lines 834-841 from `option.ccp` that it sets the `OMP_NUM_THREADS` variable (it never reads it in version 1.21).
* `gemma` version 0.98.1 (2018-12-10) (version I'm using): I haven't found any options for controlling the number of threads it uses. The closest thing I found is https://github.com/genetics-statistics/GEMMA/issues/203 where they mention linking to single-threaded C OpenBLAS libraries and https://groups.google.com/forum/#!searchin/gemma-discussion/threads%7Csort:date/gemma-discussion/YCm25_ZJLuU/sv233pRmBgAJ where a user requested a way to control the number of threads (though setting `OMP_NUM_THREADS` seems to help). 

Sooo.... `GCTA`, `Gemma` and `plink` for the lasso model all have multi-thread capabilities that are set automatically and maybe can be controlled with `OMP_NUM_THREADS` plus using `--threads` for `plink`.

## Suggestion

I suggest adding something like:

```R
make_option("--threads", action="store_true", default=1,
              help="The number of threads to use (affects plink, GCTA, Gemma) [default: %default]"),	
```

Then, in the `plink` calls, explicitly pass that argument. For example change https://github.com/gusevlab/fusion_twas/blob/master/FUSION.compute_weights.R#L84 from

```R
arg = paste( opt$PATH_plink , " --allow-no-sex --bfile " , input , " --lasso " , hsq , " --out " , out , sep='' )
```

to

```R
arg = paste( opt$PATH_plink , " --allow-no-sex --bfile " , input , " --lasso " , hsq , " --out " , out , "--threads", opt$threads, sep='' )
```

(Actually, something could be similarly done for controlling the `plink` memory as in https://github.com/LieberInstitute/fusion_twas/blob/jhpce/FUSION.compute_weights.R#L85)

Then also set the `OPT_NUM_THREADS` environment variable which should work while the process is alive based on `?Sys.setenv()` and https://stackoverflow.com/questions/20647493/accessing-environment-variables-set-in-r-session-from-shell.

```R
$ Rscript -e "Sys.getenv('OPT_NUM_THREADS'); opt <- list(threads = 1); Sys.setenv('OPT_NUM_THREADS' = opt$threads); Sys.getenv('OPT_NUM_THREADS')"
[1] ""
[1] "1"
$ Rscript -e "Sys.getenv('OPT_NUM_THREADS')"
[1] ""
```

What do you think? Also, if you prefer, I can submit a PR with these changes.

Best,
Leo

**Comment by sashagusev** [comment]
This sounds great, thank you for the suggestion. I will try to push this through an update in the next few days (together with the plink compatibility issues mentioned in other threads).

**Comment by maegsul** [comment]
Hi, I am also interested in controlling the number of threads and @lcolladotor 's suggestions seem very good. Will there be an update soon @sashagusev?

Also, @lcolladotor , can you please elaborate more on setting OPT_NUM_THREADS environment? It should be something like below in the `FUSION.compute_weights.R` script itself?:

`Sys.setenv('OPT_NUM_THREADS' = opt$threads) `

...or it should be in the bash script as below?:

```
...
Rscript -e "Sys.getenv('OPT_NUM_THREADS'); opt <- list(threads = 1); Sys.setenv('OPT_NUM_THREADS' = opt$threads); Sys.getenv('OPT_NUM_THREADS')"

Rscript FUSION.compute_weights.R --bfile $OUT --tmp $OUT.tmp --out $FINAL_OUT --verbose 2 --save_hsq --PATH_gcta $GCTA --PATH_gemma $GEMMA --models blup,lasso,top1,enet --covar $COVAR --hsq_p 1.0 --threads $THREAD

Rscript -e "Sys.getenv('OPT_NUM_THREADS')"
...

```
Though, I didn't quite understand why we did not set OMP_NUM_THREADS environment but OPT_NUM_THREADS environment.

**Comment by sashagusev** [comment]
Hi all, thanks bringing this up and apologies for the delay. I'm looking back and see that the threading applies to all of the external software and can actually be managed through the `--PATH_plink`, `--PATH_gcta`, and `--PATH_gemma` flags in FUSION, simply by adding the thread flags to those paths (e.g. `--PATH_plink "plink2 --threads 10"`). I would prefer to keep the functionality as is so that if these tools change the way they handle multithreading it will not cause problems for FUSION. What do you think?

**Comment by lcolladotor** [comment]
Sounds good, thanks for the info! I didn't know you could use the syntax you showed us (`--PATH_plink "plink2 --threads 10"`). 

Regarding @maegsul, I typically set the `OPT_NUM_THREADS` outside of R before loading it. If you use `Sys.setenv()` R will know about it but not other tools that R invokes (or maybe not always). Anyways, That's why I felt safer setting this environment variable before opening R.
