### ISSUE TITLE
Using Genotype Dosages for Weight Calculation

### ISSUE THREAD

**Issue by maegsul** [gusevlab/fusion_twas#18]
Hi,

Is it possible to use genotype dosages (for instance, "DS" values in an imputed VCF) for TWAS weight calculations? I try to refrain from converting these to genotypes in PLINK file format that seems to be the required input of FUSION.compute_weights.R. 

Thanks in advance!

**Comment by sashagusev** [comment]
Hello, the code is currently written only to accept data in PLINK format, however dosages are statistically valid to use for weights as long as the scaled GWAS genotype is equal to the weights dosage in expectation (which should be the case for imputation in well matched populations).

In principle, you could modify the code to bypass the genotype reading stage (https://github.com/gusevlab/fusion_twas/blob/master/FUSION.compute_weights.R#L251) to instead load in your dosage file and phenotype file and all of the remaining weights computations should continue to work.
