### ISSUE TITLE
Unable to read BSLMM output files

### ISSUE THREAD

**Issue by gouthamatla** [gusevlab/fusion_twas#19]
Hi,

I have noticed that the gemma output, when used bslmm option, is written to a folder "output/". But the FUSION.compute_weights.R trying to read from the current directory instead of output folder.  This was explained in [gemma manual](http://www.xzlab.org/software/GEMMAmanual.pdf) (section 4.3.3)

The exact error I get is:

```
- Crossval fold 1 
[1] "/rds/general/user/gatla/home/softs/Gemma_0.98.1/gemma -miss 1 -maf 0 -r2 1 -rpace 1000 -wpace 1000 -bfile ENSG00000134256_tmp_file.cv -bslmm 1 -o ENSG00000134256_tmp_file.cv.BSLMM"

Error in file(file, "rt") : cannot open the connection
Calls: weights.bslmm -> read.table -> file
In addition: Warning message:
In file(file, "rt") :
  cannot open file 'ENSG00000134256_tmp_file.cv.BSLMM.param.txt': No such file or directory
Execution halted

```

Because the path to file is "output/ENSG00000134256_tmp_file.cv.BSLMM.param.txt". Could you let me know how can I fix this ? Can I just edit the FUSION.compute_weights.R script and append "output/" ? Not sure if it affects other parts of the analysis.

**Comment by sashagusev** [comment]
Hello, yes this is a known issue with running GEMMA. I recommend running `ln -s ./ output` in your working directory, which creates a symbolic link through the output directory. That should address any issues without requiring code changes. Hope that helps.

**Comment by Miles823** [comment]
Hi,
I have made the symbolic link by running "ln -s ./ output". when I run the FUSION.compute_weights.R, it told me that  "cannot open file './tmp4/ENSECAG00000013484.tmp.cv.BSLMM.param.txt': No such file or directory". what is the problem?

**Comment by xasancakjnc** [comment]
Hi,
I simply removed the blup model from the --models flag, will it affect the final result?

**Comment by alyssacl** [comment]
I also had to remove blup to get this to run.
Not sure why blup will not work.

**Comment by Miles823** [comment]
Hi,
Thank you for your reply. What I do is also remove the blup and Bslmm.
These two methods should be used without other methods.
Thanks.

All the best,
Miles.

Alyssa Clay-Gilmour ***@***.***>于2024年6月15日 周六23:43写道：
