### ISSUE TITLE
issue with genes skipped

### ISSUE THREAD

**Issue by montenegrina** [gusevlab/fusion_twas#20]
Hi Alexander,

I was running fusion via:

Rscript FUSION.assoc_test.R \
--sumstats c7.txt \
--weights ./weight/retina.2pos \
--weights_dir ./weight/ \
--ref_ld_chr ./LDREF/1000G.EUR. \
--chr 7 \
--out CHR.7.dat

my c7.txt looks like this (Z scores come from my UKB GWAS done in plink2):
SNP A1 A2 Z
rs62429403 C A -0.317767
rs62429404 C G -0.0968181
rs73260517 C G 0.362803
rs56339393 C T 0.361902

and my weights were precomputed from this paper
https://www.nature.com/articles/s41588-019-0351-9#Sec21

but when I run this I am getting for chr 7 and the other ones a lot of missing genes, for example for chr 7
NOTE: 836 / 916 genes were skipped
If a large number of genes were skipped, verify that your GWAS Z-scores, expression weights, and LDREF data use the same SNPs (or nearly)
Or consider pre-imputing your summary statistics to the LDREF markers using summary-imputation software such as [http://bogdan.bioinformatics.ucla.edu/software/impg/]

If I check how many SNPs overlap between c7.txt and 1000G.EUR.7.bim
I am getting 30047 SNPs out of 231525 which can be found in c7.txt.

Also this website is not available anymore http://bogdan.bioinformatics.ucla.edu/software/impg/

Can you please advise what to do in this case?

Thanks
Ana

**Comment by liangyanabcd** [comment]
same question. Can you please advise what to do in this case?

**Comment by sashagusev** [comment]
Hi Ana, it looks like most of the SNPs from your GWAS are not in our ld-ref panel. You can either rename your GWAS SNPs to match the panel, or if that still doesn't produce mostly overlapping SNPs, you will need to use your own ld-ref panel.

Best,
Sasha
________________________________

**Comment by liangyanabcd** [comment]
Thank you ~
Best~




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Sasha Gusev"<notifications@github.com&gt;; 
发送时间: 2020年2月18日(星期二) 晚上10:40
收件人: "gusevlab/fusion_twas"<fusion_twas@noreply.github.com&gt;; 
抄送: "｀. Mr.言"<775454756@qq.com&gt;; "Comment"<comment@noreply.github.com&gt;; 
主题: Re: [gusevlab/fusion_twas] issue with genes skipped (#20)



Hi Ana, it looks like most of the SNPs from your GWAS are not in our ld-ref panel. You can either rename your GWAS SNPs to match the panel, or if that still doesn't produce mostly overlapping SNPs, you will need to use your own ld-ref panel.
 
 Best,
 Sasha
 ________________________________

**Comment by montenegrina** [comment]
Hi Sasha,

thank you so much for getting back to me. When you say rename my panel what
do you mean exactly?
Also for creating my own reference panel would I just use .bim, .fam, and
.bed files from my UKB GWAS data or do something like this?
http://dougspeed.com/reference-panel/

Thanks
Ana

**Comment by sashagusev** [comment]
For renaming, just make sure that all variants are using rsid format, sometimes you will see variants named “chr22:1231234:A_C” and these will not map to our LDREF panel.

For creating your own reference panel, yes it’s just plink format bed/bim/fam binary genotypes for the SNPs you’re using, ideally for a few thousand individuals of homogenous ancestry.

Keep in mind that all of the pre-computed weights we’ve released on the FUSION web-site use the SNP identifiers from our LDREF panel, so if you want to use existing weights files you will need to rename.

**Comment by montenegrina** [comment]
Hi Sasha,

I already did what you mentioned in the first point:

Rscript FUSION.assoc_test.R \
--sumstats c7.txt \
--weights ./weight/retina.2pos \
--weights_dir ./weight/ \
--ref_ld_chr ./LDREF/1000G.EUR. \
--chr 7 \
--out CHR.7.dat

in c7.txt I have extracted only SNPs that can be found in your
/LDREF/1000G.EUR.7.bim and got the same error...

Can you please tell me are the files produced with this code:
http://dougspeed.com/reference-panel/
the same ones you have in /LDREF?

I am using Retina weights from this paper
https://www.nature.com/articles/s41588-019-0351-9
and they also used your software.

Please advise,
Ana

**Comment by sashagusev** [comment]
Hi Ana, if homogenizing the SNP names doesn't resolve the issue then you will need to use your own LD reference panel that matches the SNPs or get in touch with the authors for their reference panel.

For the LDREF files, yes you can use the code at http://dougspeed.com/reference-panel/ to generate these files.

**Comment by zhangcc89claire** [comment]
> same question. Can you please advise what to do in this case?

Hi,

When I utilized UKB GWAS for Z scores, I had the similar issue.
Have you found a solution to your problem?

Thanks!
Cheng

**Comment by zhangcc89claire** [comment]
>
Hi,

When I utilized UKB GWAS for Z scores, I had the similar issue.
Have you found a solution to your problem?

Thanks!
Cheng

**Comment by sashagusev** [comment]
Hi Cheng, the same solution applies, your GWAS SNPs need to have the same identifiers as the LDREF/*.bim files. That means either renaming your GWAS SNPs to match, or renaming the LDREF data to match, or generating new LDREF data (see the link above). Hope that helps.

**Comment by corunesa** [comment]
Hi! 
I have a similar issue. I have that error when I put the flag --coloc, if I just run the TWAS without performing the colocalization test there is no problem. does anyone know what could be the reason?
I'm using SNP that match with LDREF.bim and as weights GTEx v8. Thank you!

**Comment by Monday446** [comment]
Hi Alexander,
 I am using my own data to build a prediction model and would like to use the model to predict gene expression data for each individual in gwas cohort, is it recommended to use FUSION in this case and do I also need to consider LD reference panel in the calculation of the weights ?
Thanks,
Monday
