### ISSUE TITLE
issue with FUSION.post_process.R --omnibus

### ISSUE THREAD

**Issue by liangyanabcd** [gusevlab/fusion_twas#21]
Dear prof：
     I want to use FUSION.post_process.R –omnibus, namely Testing for effect in multiple reference panels (omnibus test). But I'm having some trouble.
Firstly, 
I use Official data-PGC2.SCZ.sumstats and two reference panels(GTEx.Whole_Blood.pos and YFS.BLOOD.RNAARR.pos). The script is as follows:

Rscript FUSION.assoc_test.R \
--sumstats PGC2.SCZ.sumstats \
--weights ./WEIGHTS/GTEx.Whole_Blood.pos \
--weights_dir ./WEIGHTS/ \
--ref_ld_chr ./LDREF/1000G.EUR. \
--chr 22 \
--out 1.dat

Rscript FUSION.assoc_test.R \
--sumstats PGC2.SCZ.sumstats \
--weights ./WEIGHTS/YFS.BLOOD.RNAARR.pos \
--weights_dir ./WEIGHTS/ \
--ref_ld_chr ./LDREF/1000G.EUR. \
--chr 22 \
--out 2.dat

Secondly,
To maximize the retention of meaningful genes, we set the standard at 0.5. The script is as follows:
cat 1.dat | awk 'NR == 1 || $NF < 0.5' > 1.top
cat 2.dat | awk 'NR == 1 || $NF < 0.5' > 2.top
We note that the official website indicate The flag looks for duplicate entries of the ID field in the --input file to select which predictors get combined into a single omnibus test, so we check. The script is as follows:
cat 1.top  2.top|awk '{print $3}'|sort|uniq -d |wc -l  ##20
    
Thirdly, we execute these script
Rscript FUSION.post_process.R --omnibus \
--sumstats PGC2.SCZ.sumstats \
--input 1.top --input 2.top \
--out 12.top.analysis \
--ref_ld_chr ./LDREF/1000G.EUR. \
--chr 22 \
--plot --locus_win 100000

I got two files 12.top.analysis.CORR.dat and 12.top.analysis.omnibus.pv.
But these files are empty. I suspect this script have some problem, but did not know how can change, can you help me?

**Comment by sashagusev** [comment]
Hi, you cannot use the input flag twice (as in `--input 1.top --input 2.top`) but need to combine the two files into one and then load it with a single `--input` flag.

**Comment by liangyanabcd** [comment]
Thank you very much！




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Sasha Gusev"<notifications@github.com&gt;; 
发送时间: 2020年4月18日(星期六) 上午8:02
收件人: "gusevlab/fusion_twas"<fusion_twas@noreply.github.com&gt;; 
抄送: "｀. Mr.言"<775454756@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [gusevlab/fusion_twas] issue with FUSION.post_process.R --omnibus (#21)





 
Hi, you cannot use the input flag twice (as in --input 1.top --input 2.top) but need to combine the two files into one and then load it with a single --input flag.
