### ISSUE TITLE
No *.RDat output generate for compute weights script

### ISSUE THREAD

**Issue by Bochao1** [gusevlab/fusion_twas#22]
Dear all, 

I am a new user for FUSION. I want compute weights using my own expressional dataset, and I am try to repeat the example script.  There is only .hsq files (no .RDat) generated after I run the commend line 59.   
https://github.com/gusevlab/fusion_twas/blob/ef9c47546c6c9aa1386f32ab633da9188fa28587/examples/GEUV.compute_weights.sh#L59

However, the manual mentioned "Assuming $TMP, $INP, and $OUT are defined, this will take as input the $INP.bed/bim/fam file and generate a $OUT.RDat file which contains the expression weights and performance statistics for this gene." 

In addition, I did not figure out how to generate $TMP file in the script.

Is any important steps were missing?
The software version are below (tested all software work well) 
GEMMA: 0.98.1 
PLINK: 1.90
gcta: https://github.com/gusevlab/fusion_twas/blob/master/gcta_nr_robust

Thank you very much!

Best,
Bochao Lin

**Comment by sashagusev** [comment]
Hi Bochao, have you filled in the paths in lines 4,5,6,9,21 and all those directories exist?

**Comment by liangyanabcd** [comment]
same problem，There is only .hsq files generated after I run the commend.  (no .RDat) . I am sure   all software work well. Can you see what the problem is?
