### ISSUE TITLE
Is beta T or F in the model top1 for calculating gene weights?

### ISSUE THREAD

**Issue by Lee211** [gusevlab/fusion_twas#24]
The beta is T in the CROSSVALIDATION ANALYSES. But the beta is F in the calcuation of final model weights. Why?

**Comment by sashagusev** [comment]
This is just a constant scaling factor and does not effect the cross-validation accuracy or the TWAS prediction. In the final computation we report the Z-score instead of the beta so that it can be used in secondary analysis (such as a Manhattan plot of the eQTL p-values).
