### ISSUE TITLE
how to impute Z-scores for the missing SNPs?

### ISSUE THREAD

**Issue by montenegrina** [gusevlab/fusion_twas#27]
Hello,

I was running fusion via:

Rscript FUSION.assoc_test.R \
--sumstats chr17.txt \
--weights ./weight/retina.2pos \
--weights_dir ./weight/ \
--ref_ld_chr ./LDREF/1000G.EUR. \
--chr 17 \
--out CHR.17.dat

and I got:

WARNING :  retina/retina.ENSG00000279879.wgt.RDat RP11-1072C15.6 17 44689858 44693340 had 90 overlapping SNPs, but none with non-zero expression weights, try more SNPS or a different model
WARNING :  retina/retina.ENSG00000279880.wgt.RDat RP11-855A2.2 17 67973934 67976072 had 173 overlapping SNPs, but none with non-zero expression weights, try more SNPS or a different model
WARNING :  retina/retina.ENSG00000280046.wgt.RDat RP11-1099M24.6 17 7858943 7866083 had 159 overlapping SNPs, but none with non-zero expression weights, try more SNPS or a different model
WARNING :  retina/retina.ENSG00000280136.wgt.RDat RP11-1228E12.2 17 88641 118578 had 93 overlapping SNPs, but none with non-zero expression weights, try more SNPS or a different model
WARNING :  retina/retina.ENSG00000280279.wgt.RDat RP11-1228E12.1 17 64099 76866 had 88 overlapping SNPs, but none with non-zero expression weights, try more SNPS or a different model
Analysis completed.
NOTE: 608 / 1069 genes were skipped
If a large number of genes were skipped, verify that your GWAS Z-scores, expression weights, and LDREF data use the same SNPs (or nearly)
Or consider pre-imputing your summary statistics to the LDREF markers using summary-imputation software such as [http://bogdan.bioinformatics.ucla.edu/software/impg/]

This website http://bogdan.bioinformatics.ucla.edu/software/impg/ doesn't exist. Can you please point me to where the code is located?

Thanks
Ana

**Comment by sashagusev** [comment]
Hi Ana, sorry about missing the software change. I would recommend using FIZI instead:

https://github.com/bogdanlab/fizi
