### ISSUE TITLE
FUSION.assoc_test.R: wgtlist does not have an N column

### ISSUE THREAD

**Issue by wwgordon** [gusevlab/fusion_twas#3]
Hi Sasha,

I've been trying to call coloc from FUSION.assoc_test.R and have noticed that the script tries to get wgtlist$N[w] for the expression data sample size for gene w: (line 330)

```
# perform COLOC test
	if ( !is.na(opt$coloc_P) && !is.na(out.tbl$TWAS.Z[w]) && out.tbl$TWAS.P[w] < opt$coloc_P ) {
		b1 = wgt.matrix[,eqtlmod] / sqrt(wgtlist$N[w])
		b2 = cur.Z / sqrt(opt$GWASN)

		vb1 = rep(1/wgtlist$N[w],length(b1))
		vb2 = `rep(1/opt$GWASN,length(b2)
```

However, wgtlist (from [something].pos) does not have an N column. Am I missing something? Is there any reason not to manually add an N column to the .pos file?

Cheers,
William Gordon (Lindstroem Group)

**Comment by sashagusev** [comment]
Hey William, you're right, the old .pos files do not have an N column but you can definitely add it as an additional column to make things work. I'll add an error report for this too.

Best,
Sasha

**Comment by wwgordon** [comment]
Great, seems to work well with the additional column. Thanks!
