### ISSUE TITLE
GRCh38

### ISSUE THREAD

**Issue by jjfarrell** [gusevlab/fusion_twas#32]
Are there any plans to migrate fusion_twas to use GRCh38 and version 8 of GTEx?

**Comment by gouthamatla** [comment]
I am also wondering if it is possible to have weights for GTEx V8 sQTLs and eQTLs.

**Comment by sashagusev** [comment]
Hi all, we're in the process of computing and releasing weights on GTEx v8 but unfortunately do not have a timeline yet. Regarding GRCh38, all of the data is indexed by rsid so prior weights are compatible across any genome build, but we do not have plans to recompute prior weights with newer genome builds.
