### ISSUE TITLE
GEUV.compute_weights.sh  -- $PRE_GEXP.ID

### ISSUE THREAD

**Issue by xukaili** [gusevlab/fusion_twas#33]
There is no file or directory for : $PRE_GEXP.ID

On line 50 of GEUV.compute_weights.sh

**Comment by xukaili** [comment]
May be you can use this before line 50:

head -n 1 $PRE_GEXP | tr '\t' '\n' | sed  '1,4d' > ${PRE_GEXP}.ID

**Comment by sashagusev** [comment]
Thanks for spotting this, a line has been added to generate the ID file as you suggest.

Best,
Sasha
