### ISSUE TITLE
What is the best way to create Plink files for FUSION.compute_weights.R?

### ISSUE THREAD

**Issue by montenegrina** [gusevlab/fusion_twas#34]
Hello,

I plan to analyze my RNAseq data (paired end dataset) and to convert it to Plink format in order to use it with: FUSION.compute_weights.R

Can you please let me know is the following set of commands optimal for that purpose, if not can you please let me knw what you would change?

#alignement file (done with STAR) sorted
samtools sort $OUTPUT.bam  -o $OUTPUT.sorted.bam

#Index the genome assembly
samtools faidx Homo_sapiens.GRCh38.dna.primary_assembly.fa

#Run 'mpileup' to generate VCF format
samtools mpileup -g -f Homo_sapiens.GRCh38.dna.primary_assembly.fa     $OUTPUT.sorted.bam > my-raw.bcf

#call SNPs
bcftools view -bvcg my-raw.bcf > my-var.bcf

#filter SNPs
bcftools view my.var.bcf | vcfutils.pl varFilter - > my.var-final.vcf

#convert VCF to Plink format
vcftools --vcf my.var-final.vcf  --out my_data --plink

Thank you so much!

**Comment by sashagusev** [comment]
Hi, are you intending to generate SNPs from the RNA-seq data or quantified expression? It appears that this pipeline is only generating SNPs. Note that FUSION conventionally takes in SNPs from a dense genotyping array, as well as a quantified expression phenotype. I recommend looking at the GTEx papers and documentation for a good reference (https://gtexportal.org/home/documentationPage#staticTextAnalysisMethods).

Best,
Sasha

**Comment by montenegrina** [comment]
Hi Sasha,

I am looking to generate weights from RNA seq data, for 174 lymphoblastoid cell lines . My question is how to go from RNA seq data (fastq files) to Plink files necessary to create .RDAT file with your FUSION.compute_weights.R code.

Thanks
Ana

**Comment by sashagusev** [comment]
Hi Ana, unfortunately FUSION is intended for RNA-seq data that has already been quantified and we do not provide guidance on how to do the quantification as there are many options and this is an area of continued development. I recommend looking at the GTEx paper and documentation for how to quantify expression. Additionally, you need to have SNP genotyping for your samples which does not come from the RNA-seq.

**Comment by montenegrina** [comment]
I already know my RNAseq workflow where I will do alignment with STAR and I
will have my gene counts generated with featureCounts from subread-2.0.1
based on primary alignment for genes annotated with
Homo_sapiens.GRCh38.102.gtf.  When you mentioned :" you need to have SNP
genotyping for your samples" do you refer to SNP calling? If yes can you
please refer me to where in GTEX paper that is mentioned?

I hoped that I would do SNP calling with GRCh38 reference file :
samtools mpileup -g -f Homo_sapiens.GRCh38.dna.primary_assembly.fa
$OUTPUT.sorted.bam > my-raw.bcf

bcftools view -bvcg my-raw.bcf > my-var.bcf

**Comment by sashagusev** [comment]
The SNP calls from RNA data will not be usable for FUSION because they will only include variants in the gene bodies (and will have noise due to expression). See details on genotyping in the GTEx project where, for example, they used an OMNI SNP array and whole genome sequencing (https://gtexportal.org/home/documentationPage#staticTextDataProduction).
