### ISSUE TITLE
File format of GTEx.v7.meta.id and GTEx.v7.meta.covar

### ISSUE THREAD

**Issue by travismize** [gusevlab/fusion_twas#35]
Hello,

I am attempting to match the FUSION GTEx v7 pipeline (GTEX_v7.sh). What are the file formats of GTEx.v7.meta.id and GTEx.v7.meta.covar, and how were these files generated/obtained?

Thank you

**Comment by sashagusev** [comment]
Hi, sorry about this confusion with this file, the *meta* data was for a subsequent exploratory analysis (including top eQTLs as covariates) and is not needed. I've removed this step from the script and added some comments describing the additional inputs. Hope that helps!

Best,
Sasha
