### ISSUE TITLE
Understanding top1 output in wgt.matrix

### ISSUE THREAD

**Issue by travismize** [gusevlab/fusion_twas#36]
Hello,

I am seeking clarification regarding the values represented in the wgt.matrix of a gene weight for the top1 model. Specifically, how is the top SNP chosen for the gene-level model (assuming top1 is the best model), in regards to the data given in this matrix? Are you simply taking the SNP with the largest absolute value of the top1 column?

Thank you.

**Comment by sashagusev** [comment]
Hi, that's right. All of the marginal associations are stored in the top1 model for downstream plotting / conditional analyses. But the "top1" model for TWAS simply takes the SNP with the largest absolute value in the top1 column.
