### ISSUE TITLE
Add covariates when computing weigths

### ISSUE THREAD

**Issue by PierreSolomon** [gusevlab/fusion_twas#39]
Hello,

Concerning the covariates, what is the best way to deal with missing value when adding covariates with the --covar flag?
Do we need to use the [.cov format from plink](https://www.cog-genomics.org/plink/1.9/formats#cov) with 2+C columns?

Thank you in advance.
Best

Pierre

**Comment by sashagusev** [comment]
Hi Pierre, yes the format is *.cov from plink with 2+C columns. Currently FUSION does not do anything about missing data and assumes the covariates are complete. In general, I think the commonly used options are: (a) remove the individuals with missing covariates from your analysis (you can do this with `plink --remove` before you pass the data to FUSION), (b) fill in the missing covariates with the covariate mean (you can do this externally in R/python prior to passing the covariates to FUSION), (c) use some fancy covariate imputation method. Hope that helps!
