### ISSUE TITLE
Issue with post_process.R that gets resolved by forcing the code to run through a while loop at least once

### ISSUE THREAD

**Issue by lcolladotor** [gusevlab/fusion_twas#4]
Hi,

While running `FUSION.post_process.R` I encountered the following error:

```R
Error in solve.default(ge_g.ld[joint.keep, joint.keep]) : 'a' is 0-diml
```

After running it line by line, I noticed that the error was prompted by https://github.com/gusevlab/fusion_twas/blob/master/FUSION.post_process.R#L432

That's because `sum(cond.z^2 > zthresh^2)` is equal to `0` and thus the code inside the `while` loop at https://github.com/gusevlab/fusion_twas/blob/master/FUSION.post_process.R#L414 doesn't run. Thus `joint.keep` is all set to `FALSE` by https://github.com/gusevlab/fusion_twas/blob/master/FUSION.post_process.R#L412 and the error at https://github.com/gusevlab/fusion_twas/blob/master/FUSION.post_process.R#L432 is really caused by running `solve()` on a 0 by 0 matrix

```R
> ge_g.ld[joint.keep,joint.keep]
<0 x 0 matrix>
```

I was able to bypass this error by making the following edit:

```
initiate_flag <- TRUE
while ( sum(cond.z^2 > zthresh^2) != 0 || initiate_flag) {
    initiate_flag <- FALSE
```

at the neighboring lines to (currently) line 414 at https://github.com/gusevlab/fusion_twas/blob/master/FUSION.post_process.R#L414

Does this edit seems reasonable to you? Basically, I'm telling it to add the most conditional feature and use that one only if all else fails. In my case, `sum(cond.z^2 > zthresh^2)` was still equal to `0` after running through the code in the `while` loop once.

Best,
Leonardo

## Reproducibility information

```R
> library('sessioninfo')
> options(width = 120)
> sessioninfo::session_info()
─ Session info ───────────────────────────────────────────────────────────────────────────────────────────────────────
 setting  value
 version  R version 3.5.1 Patched (2018-10-29 r75535)
 os       Red Hat Enterprise Linux Server release 6.9 (Santiago)
 system   x86_64, linux-gnu
 ui       X11
 language (EN)
 collate  en_US.UTF-8
 ctype    en_US.UTF-8
 tz       US/Eastern
 date     2019-01-22

─ Packages ───────────────────────────────────────────────────────────────────────────────────────────────────────────
 package      * version   date       lib source
 assertthat     0.2.0     2017-04-11 [2] CRAN (R 3.5.0)
 bindr          0.1.1     2018-03-13 [1] CRAN (R 3.5.0)
 bindrcpp       0.2.2     2018-03-29 [1] CRAN (R 3.5.0)
 cli            1.0.1     2018-09-25 [1] CRAN (R 3.5.1)
 colorout     * 1.2-0     2018-05-02 [1] Github (jalvesaq/colorout@c42088d)
 colorspace     1.4-0     2019-01-13 [2] CRAN (R 3.5.1)
 corrplot     * 0.84      2017-10-16 [2] CRAN (R 3.5.0)
 crayon         1.3.4     2017-09-16 [1] CRAN (R 3.5.0)
 digest         0.6.18    2018-10-10 [1] CRAN (R 3.5.1)
 dplyr          0.7.8     2018-11-10 [1] CRAN (R 3.5.1)
 getopt         1.20.2    2018-02-16 [1] CRAN (R 3.5.0)
 ggplot2        3.1.0     2018-10-25 [1] CRAN (R 3.5.1)
 glue           1.3.0     2018-07-17 [1] CRAN (R 3.5.1)
 gtable         0.2.0     2016-02-26 [2] CRAN (R 3.5.0)
 htmltools      0.3.6     2017-04-28 [2] CRAN (R 3.5.0)
 htmlwidgets    1.3       2018-09-30 [1] CRAN (R 3.5.1)
 httpuv         1.4.5.1   2018-12-18 [2] CRAN (R 3.5.1)
 later          0.7.5     2018-09-18 [2] CRAN (R 3.5.1)
 lattice        0.20-38   2018-11-04 [3] CRAN (R 3.5.1)
 lazyeval       0.2.1     2017-10-29 [2] CRAN (R 3.5.0)
 magrittr       1.5       2014-11-22 [1] CRAN (R 3.5.0)
 Matrix         1.2-15    2018-11-01 [3] CRAN (R 3.5.1)
 munsell        0.5.0     2018-06-12 [2] CRAN (R 3.5.0)
 optparse     * 1.6.1     2019-01-15 [2] CRAN (R 3.5.1)
 pillar         1.3.1     2018-12-15 [1] CRAN (R 3.5.1)
 pkgconfig      2.0.2     2018-08-16 [1] CRAN (R 3.5.1)
 plink2R      * 1.1       2018-12-06 [1] Github (gabraham/plink2R@d74be01)
 plyr           1.8.4     2016-06-08 [2] CRAN (R 3.5.0)
 png            0.1-7     2013-12-03 [2] CRAN (R 3.5.0)
 promises       1.0.1     2018-04-13 [2] CRAN (R 3.5.0)
 purrr          0.2.5     2018-05-29 [2] CRAN (R 3.5.0)
 R6             2.3.0     2018-10-04 [2] CRAN (R 3.5.1)
 RColorBrewer * 1.1-2     2014-12-07 [2] CRAN (R 3.5.0)
 Rcpp         * 1.0.0     2018-11-07 [1] CRAN (R 3.5.1)
 RcppEigen    * 0.3.3.5.0 2018-11-24 [1] CRAN (R 3.5.1)
 rlang          0.3.1     2019-01-08 [1] CRAN (R 3.5.1)
 rmote        * 0.3.4     2018-05-02 [1] deltarho (R 3.5.0)
 scales         1.0.0     2018-08-09 [2] CRAN (R 3.5.1)
 servr          0.11      2018-10-23 [1] CRAN (R 3.5.1)
 sessioninfo  * 1.1.1     2018-11-05 [1] CRAN (R 3.5.1)
 tibble         2.0.1     2019-01-12 [1] CRAN (R 3.5.1)
 tidyselect     0.2.5     2018-10-11 [2] CRAN (R 3.5.1)
 withr          2.1.2     2018-03-15 [2] CRAN (R 3.5.0)
 xfun           0.4       2018-10-23 [1] CRAN (R 3.5.1)

[1] /users/lcollado/R/x86_64-pc-linux-gnu-library/3.5.x
[2] /jhpce/shared/jhpce/core/conda/miniconda-3/envs/svnR-3.5.x/R/3.5.x/lib64/R/site-library
[3] /jhpce/shared/jhpce/core/conda/miniconda-3/envs/svnR-3.5.x/R/3.5.x/lib64/R/library
>
```

**Comment by sashagusev** [comment]
Hi Leonardo, thanks for finding this issue and going through the code to diagnose it, much appreciated! As you note, the underlying cause is that the Z-score threshold to consider a model for conditional analysis is so high that it excludes all models and then the conditional analysis breaks. I've updated the code to:

1. Have a --zthresh flag that lets you force a specific threshold if you want to override the standard Bonferroni threshold and try lower levels of significance
2. If there are still no models that pass this threshold (either in total or in a given locus) the analysis is skipped.

I think this is the most flexible way to only run on significant models while allowing the user to still specify lower significance if they prefer. Let me know if this makes sense for what you're trying to do.

Best,
Sasha

**Comment by lcolladotor** [comment]
Hi Sasha,

Thanks for introducing these changes! I merged them into our fork (https://github.com/LieberInstitute/fusion_twas/, more on this at https://github.com/LieberInstitute/brainseq_phase2/tree/master/twas) and I'm running into issues with [our chr18 test case](https://github.com/LieberInstitute/fusion_twas/blob/jhpce/FUSION.post_process.R#L132-L158). Basically, `sum(cond.z^2 > zthresh^2) == 0` is false, so the warning is triggered at https://github.com/gusevlab/fusion_twas/blob/ac1229ff7da0cf823a1380ced3512af90c5d0daa/FUSION.post_process.R#L319 so the object `joint.keep` is not defined which later leads to an error when running https://github.com/gusevlab/fusion_twas/blob/ac1229ff7da0cf823a1380ced3512af90c5d0daa/FUSION.post_process.R#L432.

```R
> if( opt$verbose > 0 ) cat( "consolidated to ", length(cons.loc.starts) , " non-overlapping loci with ", opt$locus_win , " bp buffer\n" , sep='' , file=stderr() )
consolidated to 23 non-overlapping loci with 1e+05 bp buffer
>
> dinv = solve(ge_g.ld[joint.keep,joint.keep])
Error in solve(ge_g.ld[joint.keep, joint.keep]) :
  object 'joint.keep' not found
>
``` 

What should `joint.keep` be in this scenario?

With the code at https://github.com/LieberInstitute/fusion_twas/blob/f677aaff715c62653fb2e05da97386b9a936480b/FUSION.post_process.R#L354-L390 (with the `initiate_flag` which forced it to go through the loop once) `joint.keep` has a single `TRUE` value, which made the rest of the code work (I know that at least 1 of the elements of this vector has to be `TRUE` for the rest of the code to run properly).

```R
+ if( opt$verbose > 1 ) cat( unlist( wgtlist$FILE[ cur.unstable ] ) , " became more significant after conditional analysis and are dropped from the model (this is usually a sign of LD mismatch or a complex locus)\n" , sep='' , file=stderr() )
+ ge.drop[ cur.unstable ] = T
+ cond.z[ cur.unstable ] = 0
+ }
+ }
/dcl01/lieber/ajaffe/lab/brainseq_phase2/twas/HIPPO/gene/out_files/gene_20536.wgt.RDat added to model with conditional Z-score of -3.23307
> if( opt$verbose > 1 ) cat( "final best conditional Z^2 = " , max(cond.z^2) , "\n" , sep='' , file=stderr() )
final best conditional Z^2 = 10.35424
>
> joint.keep = ge.keep
>
> joint.keep
 [1] FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE
[13] FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE
[25] FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE
[37] FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE
[49] FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE
[61] FALSE FALSE FALSE FALSE FALSE FALSE FALSE  TRUE FALSE
```

Best,
Leo

**Comment by sashagusev** [comment]
Thanks for catching this, the line 432 `dinv` is unnecessary and not used later on. I've removed it and pushed out the update. The `joint.keep` should just be inside each conditional analysis for the variables that have been retained in the joint model.

**Comment by sashagusev** [comment]
Ah, I've just fixed the comma issue too, trying to debug between meetings :)

**Comment by lcolladotor** [comment]
Thanks for the changes Sasha! The code is running without errors now. Thanks!

**Comment by lcolladotor** [comment]
Thank you again @sashagusev!

https://twitter.com/fellgernon/status/1135944877554798592

**Comment by sashagusev** [comment]
:) thanks for the shout-out and congrats on this cool paper!

**Comment by lcolladotor** [comment]
Thank you =) ^_^
