### ISSUE TITLE
What is the best way to normalise RNA-seq data when running FUSION.compute_weights.R? 

### ISSUE THREAD

**Issue by Fei-Yang666** [gusevlab/fusion_twas#42]
Dear developer, 

Can you please let me know the preferred normalisation method for RNA-seq data when running FUSION.compute_weights.R?  logCPM or other method? I want to run TWAS for both gene level and transcript level but got confused about the data normalisation methods and do not know whether there is a recommended approach. It is quite important and very looking forward for your reply. Will appreciate that very much 

many thanks,

Fei

**Comment by sashagusev** [comment]
Hi Fei, the expression normalization step is very project specific so we don't have a single recommendation. I would generally follow the same process you would use for eQTL discovery or take a look at the analysis workflow from the GTEx Consortium (https://gtexportal.org/home/documentationPage#staticTextAnalysisMethods).

**Comment by Fei-Yang666** [comment]
Thanks very much for your response :)
