### ISSUE TITLE
error in FUSION.assoc_test.R  step (Error in out.tbl$EQTL.ID[w] <- names(topeqtl) : replacement has length zero)

### ISSUE THREAD

**Issue by Fei-Yang666** [gusevlab/fusion_twas#44]
Hi Alexander Gusev,

Did you figure out this issue (Error in out.tbl$EQTL.ID[w] <- names(topeqtl) : replacement has length zero) raised here  (https://github.com/gusevlab/fusion_twas/issues/5) ?
I came across the same issue when using my own weights computed for my leafcutter calculated splicing intron usage, and it only happened for some chromosomes, not for all chromosomes. Pretty weird, can you give me any insight? I already checked that my SNP lables in wgt.matrix and GWAS summary statistics and LDREF1000 are consistent. I used [LDSC munge_stats.py](https://github.com/bulik/ldsc) to format my GWAS and 1,189,408/1,217,311 of GWAS SNPs are also in my LDREF panel. 

Another issue is when using my own LD reference panel, almost all genes skipped, but when I used the LDREF1000 provided in the tutorial, it works. My own LD reference data has more SNPs, but the bim file third column is 0 where there is a value for this column in LDREF1000. But according the the plink (https://www.cog-genomics.org/plink/1.9/formats), the third column--"Position in morgans or centimorgans (safe to use dummy value of '0') " is okay to be 0. Can you please give any insights as well? That will be much appreciated

many thanks,

Fei

**Comment by JFF1594032292** [comment]
This maybe helpful  https://github.com/gusevlab/fusion_twas/issues/6
I met the same error, and changing the code seems to fix it.

**Comment by Fei-Yang666** [comment]
Hi JFF,

Thanks for your response, it also fixed my error : ) 

I also have a question about the P0 and P1 position in pos file, does this have to be the same genome build as 1000k LD reference panel?  I mean 1000k LD reference panel is based on  grch37,  but my weights are based on grch38 so I just provided grch38 position for my genes.  I know the weights are compatible across all genome based on the answer here (https://github.com/gusevlab/fusion_twas/issues/32), but how about the plotting and conditional step?   Do you have any idea?  

Many thanks,

Fei

**Comment by sashagusev** [comment]
Thanks for re-upping this, I've now added the fix to the code.

Regarding genome build, please see the discussion here:
https://github.com/gusevlab/fusion_twas/issues/43

As you note, plotting and visualization are impacted by genome build and would require lifting over the physical positions.
