### ISSUE TITLE
linux or window system to run FUSION.test.R?

### ISSUE THREAD

**Issue by wangrenxi760201** [gusevlab/fusion_twas#46]
I guess that you use linux system to run FUSION.test.R. Do you have a window version?

Finally, we run FUSION.test.R using this data on chromosome 22:

Rscript FUSION.assoc_test.R \
--sumstats PGC2.SCZ.sumstats \
--weights ./WEIGHTS/GTEx.Whole_Blood.pos \
--weights_dir ./WEIGHTS/ \
--ref_ld_chr ./LDREF/1000G.EUR. \
--chr 22 \
--out PGC2.SCZ.22.dat

**Comment by sashagusev** [comment]
We don't have a specific windows version but you should be able to get it working on any system that supports R. It just uses R and R libraries.
