### ISSUE TITLE
QTL scores values to FUSION model format

### ISSUE THREAD

**Issue by fernandogs97** [gusevlab/fusion_twas#48]
Hello, I am starting in the xWAS (PWAS, TWAS, MWAS) field, at first I have only been using the models published by you on my patients summary data with predixcan (https://github.com/hakyimlab/PrediXcan). 
Despite this, I am trying to use more available information, for this purpose, I want to use QTL score information (for example: https://www.omicspred.org/) to create models in the predixcan format so I can apply them to my data. 
The main problem is that I do not find information about how to use the QTL score information published by multiple authors. I would be very grateful if someone could give me some advice on this area.

**Comment by sashagusev** [comment]
Hi, thanks for the link to omicspred.org, I actually wasn't familiar with this resource. Unfortunately we don't have any code at the moment to convert their data into FUSION compatible weights files, however based on the file format described here (https://www.omicspred.org/Scores) it looks very doable. The corresponding RDat file for FUSION needs to contain the following variables:
* wgt.matrix: the prediction weights, with rownames = snp identifiers and colnames = model identifiers (in this case just one model)
* snps: a matrix of the snp identifiers in plink/bim format
* cv.performance: a matrix with rownmaes = c("rsq","pval") and colnames = model identifiers, listing the R^2 and p-value for the model in cross validation, this can be filled in with dummy numbers if unavailable
* hsq, hsq.pv, N.tot : variables corresponding to the heritability of the model, the p-value, and the GWAS sample size, these can also be filled in with faks numbers.

All of the required entries are thus available in the omicspred score files. Let me know if you have any other questions!
