### ISSUE TITLE
Error with LDREF

### ISSUE THREAD

**Issue by geneticsmcgill** [gusevlab/fusion_twas#5]
Hi there,

I keep getting an error when following the sample code for some reason. 

Rscript FUSION.assoc_test.R --sumstats psych-vs-bd_2018.sumstats.sumstats.gz --weights final.psych.encode.genes.rdat.list --weights_dir ~/fusion_twas-master/WEIGHTS/ --ref_ld_chr ./LDREF/1000G.EUR. --chr 22 --out psych.dat
Error in file(file, "rt") : cannot open the connection
Calls: read_plink -> read.table -> file
In addition: Warning message:
In file(file, "rt") :
  cannot open file '/Users/CL/fusion_twas-master/LDREF/1000G.EUR..bim': No such file or directory
Execution halted

I'm unsure why this may be occurring. I would appreciate any insight. 

I also get this error if I try putting the 22  ./LDREF/1000G.EUR.22

Error in load(wgt.file) : restore file may be empty -- no data loaded
In addition: Warning messages:
1: In readChar(con, 5L, useBytes = TRUE) : error reading the file
2: file ‘WEIGHTS’ has magic number ''
  Use of save versions prior to 2 is deprecated
Execution halted

Thank you so much.

**Comment by sashagusev** [comment]
Hmm, I don't see anything obviously wrong with the syntax. Does your `final.psych.encode.genes.rdat.list` file have a header (including a CHR column) and entries with CHR=22? Are you able to run it using the precomputed weights and pos file (e.g. https://data.broadinstitute.org/alkesgroup/FUSION/WGT/GTEx.Whole_Blood.tar.bz2)?

**Comment by geneticsmcgill** [comment]
Thank you. I was missing the header. I was able to run it but I'm running into an eQTL issue now: 

Error in out.tbl$EQTL.ID[w] <- names(topeqtl) :
  replacement has length zero
Execution halted

What does it mean by replacement? I tried testing some other fixes but I keep running into it still.

**Comment by sashagusev** [comment]
Are you using your own weights data or our pre-computed weights? It looks like the weights data may not have properly labeled SNPs (i.e. the rownames of the `wgt.matrix` matrix in the *RDat weights file you're working with).

**Comment by geneticsmcgill** [comment]
Thanks for the reply! I'm using the psych-encode TWAS data (http://resource.psychencode.org/Datasets/Derived/PEC_TWAS_weights.tar.gz). However, they label their SNPs as chrNumber:Position so I ended up changing the LD panel and GWAS data to match that.

**Comment by sashagusev** [comment]
I see, renaming the SNPs and GWAS in the panel should work as long as there is sufficient overlap between all of them. Is this happening for a specific weight model or for all of them?

**Comment by geneticsmcgill** [comment]
It happens when using all weight models. When specifying top eqtl, it works.

**Comment by sashagusev** [comment]
Do you think you could email me a small example where this is happening (alexander_gusev@dfci.harvard.edu). It must be some kind of labeling issue but hard to diagnose since many aspects of the data are different.

**Comment by Fei-Yang666** [comment]
Hi Alexander Gusev or geneticsmcgill,

Did you figure out this isssue (Error in out.tbl$EQTL.ID[w] <- names(topeqtl) : replacement has length zero) ? 
I came across the same issue when using my own weights computed for my leafcutter calculated splicing intron usage, and it only happened for some chromosomes, not for all chromosomes.  Pretty weird, can you give me any insight?  I already checked that my SNP lables in wgt.matrix and GWAS summary statistics and LDREF1000 are consistent. 

Another issue is when using my own LD reference panel, almost all genes skipped, but when I used the LDREF1000 provided in the tutorial, it works. My own LD reference data has more SNPs,  but the bim file third column is 0 where there is a value for this column in LDREF1000.  But according the the plink (https://www.cog-genomics.org/plink/1.9/formats), the third column--"Position in morgans or centimorgans (safe to use dummy value of '0') " is okay to be 0. Can you please give any insights as well? That will be much appreciated 

many thanks,

Fei

**Comment by showers14** [comment]
hi
recently ! I'm using the psych-encode TWAS data (http://resource.psychencode.org/Datasets/Derived/PEC_TWAS_weights.tar.gz). 
could you please tell how to change the LD panel and GWAS data to match that?
many thanks
