### ISSUE TITLE
Error in check_dataset(d = dataset1, 1) : 

### ISSUE THREAD

**Issue by MIAO0916** [gusevlab/fusion_twas#50]
Rscript ${pw_scr}/2.FUSION.assoc_test.R \
			--sumstats ${pw_result}/${disease_name}.sumstats.gz \
			--weights ${pw_tissue}/${tissue}.P01.pos \
			--weights_dir ${pw_tissue} \
			--ref_ld_chr LDREF/1000G.EUR. \
			--chr ${i} \
			--coloc_P 0.05 \
			--PANELN PANELN.file  \
			--GWASN 353388 \
			--out ${disease_name}.${tissue}.${i}.dat

PANELN.file:
PANEL	N
OA_synovium_v1.WH_fusion	202
OA_cartilage_v1.WH_fusion	204

Error in check_dataset(d = dataset1, 1) : 
  dataset 1: missing required element(s) snp
Calls: suppressMessages ... capture.output -> withVisible -> coloc.abf -> check_dataset
Execution halted

We used the top1 ，lasso and enet models to modeling, so  fewer SNPs were used，before I added coloc analysis，although some snps which calling：(WARNING :  OA_synovium_v1 OA_synovium_v1.WH_fusion/ENSG00000136731.8.fusion_model.wgt.RDat UGGT1 2 128848774 128953251 202 had 472 overlapping SNPs, but none with non-zero expression weights, try more SNPS or a different model ) have no results, the results of fusion analysis : All 22 chromosomes have their own result  .dat file .

But when I add coloc, there are only  one chromosome have its .dat file, and the values of COLOC.PP0	COLOC.PP1	COLOC.PP2	COLOC.PP3	COLOC.PP4 columns are presented as "NA".

I wonder how can I solve this problem？Can anyone help me？Thanks!

Best,
miao

**Comment by sashagusev** [comment]
Hi Miao, it's a bit unclear to me what the problem is here since you are getting a variety of errors. The main issue to check is: does your GWAS summary data contain all the same variants that are in your weights files (and if not, restricting to or imputing the missing variants)? If the GWAS and TWAS weights are partially overlapping then you will get unexpected behavior.

**Comment by xiechengyong123** [comment]
This situation is caused by an update to the coloc package, you can try installing coloc back to the previous version, e.g. coloc=5.1.0.1
