### ISSUE TITLE
LASSO output did not exist

### ISSUE THREAD

**Issue by MaudLau** [gusevlab/fusion_twas#51]
Hi,
I am a new user for fusion. I want to compute weights using my own expressional dataset. But I cannot find lasso output. The exact error I get is:

`### Performing 5 fold cross-validation
- Crossval fold 1 
${path}/temporary/NM_000287:PEX6:chr6:-.txt.tmp.cv.LASSO.lasso  LASSO output did not exist
- Crossval fold 2 
${path}/temporary/NM_000287:PEX6:chr6:-.txt.tmp.cv.LASSO.lasso  LASSO output did not exist
- Crossval fold 3 
${path}/temporary/NM_000287:PEX6:chr6:-.txt.tmp.cv.LASSO.lasso  LASSO output did not exist
- Crossval fold 4 
${path}/temporary/NM_000287:PEX6:chr6:-.txt.tmp.cv.LASSO.lasso  LASSO output did not exist
- Crossval fold 5 
${path}/temporary/NM_000287:PEX6:chr6:-.txt.tmp.cv.LASSO.lasso  LASSO output did not exist
lasso	top1
rsq	NA	0.41930171599824
pval	NA	2.41386094625509e-15
Computing full-sample weights
${path}/temporary/NM_000287:PEX6:chr6:-.txt.tmp.lasso  LASSO output did not exist
Cleaning up`

Did I do something wrong? 

Best,
Maud

**Comment by sashagusev** [comment]
Hi Maud, thanks for the comment. The LASSO requires a working version of plink 1.9 that can handle the `--lasso` flag. You can specify where plink is by setting `--PATH_plink` in FUSION (by default it just assumes `plink` can be run from the command line). Do you have a working and linked plink version?

**Comment by MaudLau** [comment]
Hi Sasha, Thanks for the reply! I misused plink2. I have downloaded correct version. Thank you so much.
