### ISSUE TITLE
Failed to download the reference panel!

### ISSUE THREAD

**Issue by AaronHY** [gusevlab/fusion_twas#53]
Hello, 

Thanks for this important program for the TWES. I am new to this area and intend to try the Fusion workflow. But I can't download the FUSION LD reference data from the provided superlink. Please tell me where else this data is available. Thanks indeed.

**Comment by yu-zhang-oYo** [comment]
Hi, do you know the solution for this problem? I cannot download the LD reference data either. Thanks.

**Comment by LLing4368** [comment]
I also met this problem.  I can't download the FUSION demo data such as LD reference data  &  summary statistics (PGC2.SCZ.sumstats  ) from the provided superlink.

**Comment by sashagusev** [comment]
This was a temporary issue with hosting that should now be restored. Apologies!
