### ISSUE TITLE
Using FUSION for Individual-level predictors

### ISSUE THREAD

**Issue by jianvhuang** [gusevlab/fusion_twas#55]
I plan to calculate a gene expression risk score using the method described in the paper below.
[`Oliver Pain, et al, Imputed gene expression risk scores: a functionally informed component of polygenic risk, Human Molecular Genetics, Volume 30, Issue 8, 15 April 2021.`](https://academic.oup.com/hmg/article/30/8/727/6145896)

I have used FUSION for the summary level TWAS. I want to combine the eQTL weight with my individual-level genotype data.
I tried `Rscript make_score.R [wgt.RDat file] > [SCORE_FILE]` but sometimes the output is a dataset with all NAs of 4 columns, and sometimes the output is an empty file. In some cases, I did obtain output with SNP, A1, A2, Z.

The wgt.RDat file was downloaded from the FUSION tutorial webpage (GTEx8, whole blood and brain-related tissues). 
I wonder why the score files are not generated correctly for some genes.
Thank you.

**Comment by jianvhuang** [comment]
This is most likely because I used the `nofilter.pos` file, instead of the `.pos` file which only contains genes with significant heritability

**Comment by alyssacl** [comment]
> This is most likely because I used the `nofilter.pos` file, instead of the `.pos` file which only contains genes with significant heritability

Is it recommended to use .pos or nofilter.pos?

The answer is: Using genes that achieved significant heritability is recommended for typical analyses.
http://gusevlab.org/projects/fusion/
