### ISSUE TITLE
COLOC I am getting results with 'NA' 

### ISSUE THREAD

**Issue by vherrera606** [gusevlab/fusion_twas#57]
If anyone has had this issue before in a troubleshoot do let me know, thank you. Basically I am trying to run an association test with coloc and the values I need for coloc keep coming in blanks on every tissue as seen on image.

cmd = paste(
  ' Rscript /fusion_twas-master_Template/FUSION.assoc_test.R',
  ' --coloc_P 0.05',
  ' --GWASN 517318',
  ' --sumstats ', INPRE,
  ' --weights /GTExv8.EUR.WEIGHTS/',df$file[SGE_TASK_ID],
  ' --weights_dir /GTExv8.EUR.WEIGHTS/',
  ' --ref_ld_chr /LDREF/1000G.EUR.',
  ' --chr ', df$chr[SGE_TASK_ID],
  ' --out /Cataracts_fusion_twas-master/fusion_twas-master_Template/5_FUSION_Post_TWAS/FUSION_res/',df$file_out[SGE_TASK_ID],'.chr',df$chr[SGE_TASK_ID],'.dat',
  sep='')

<img width="1550" alt="Error_coloc" src="https://github.com/gusevlab/fusion_twas/assets/10424340/7aeab608-fa0b-4646-b954-7229e4309b57">

**Comment by sashagusev** [comment]
Hi, I don't think this is an issue with coloc as you are seeing NA's for all other columns as well. Are you getting any other errors?

**Comment by vherrera606** [comment]
Like another post pertaining to coloc, using version coloc=5.1.0.1resolved my issue. Hopefully a future update will resolve this issue by default.
