### ISSUE TITLE
Error when there is a single SNP in wgt.matrix

### ISSUE THREAD

**Issue by jhchung** [gusevlab/fusion_twas#6]
I found a bug in `FUSION.assoc_test.R` when there is a single SNP in the `wgt.matrix`. The `names()` function does not get the correct variant ID and causes the script to exit.

Changing the following line:
```out.tbl$ETQL.ID[w] = names( topeqtl )```
to 
```out.tbl$EQTL.ID[w] = rownames(wgt.matrix)[topeqtl]```

appears to fix the issue.

**Comment by sashagusev** [comment]
ah thank you for catching this, this explains some of the other errors. Though the TWAS test isn't really doing anything with just one snp in the weight matrix :)

**Comment by jhchung** [comment]
Happy to help.
