### ISSUE TITLE
Self-generated LDREF does not work

### ISSUE THREAD

**Issue by sureyana956** [gusevlab/fusion_twas#7]
Hi!

Thank for providing this wonderful tool. However, I had some difficulty running FUSION.assoc_test.R with self-generated LDREF data. 

I download .pgen, pvar, and psam files from https://www.cog-genomics.org/plink/2.0/resources#1kg_phase3. Then I used plink to select EAS samples only. As a control step, I did the same thing for EUR as well. 

Using EUR gives me similar results as your example. When using EAS, I got warnings saying that 72/72 genes were skipped, because those genes had missing GWAS Z-scores that could not be imputed. 

So my questions are:
1. The sample size between EAS and EUR are similar, the SNP list is exactly same, but the TWAS results are so much different. Have you ever tested your example files using LD reference data of other populations? Is it simply because EUR and EAS are genetically different? If it's not the reason,
2. Could you please give me a snapshot of how your LDREF_EUR data was generated? 

Thank you so much in advance!
Best,
Hu

**Comment by sashagusev** [comment]
Hi Hu, thanks for pointing this out, it's definitely unexpected behavior. The error you're getting means there is insufficient overlap between the LDREF SNPs and your GWAS SNPs. Are you sure the same SNPs are being used as in the EUR data and the IDs haven't changed somehow? And the allele codes are still ACGT?

The LDREF data was generated by extracting the European samples and then running basic qc on minor allele frequency and HWE and then restricting to HapMap3 SNPs which are generally well imputed.
________________________________

**Comment by sureyana956** [comment]
Thank you so much for your prompt response. I used 4 different self-generated LDREF data sets :

- 1000G_ALL_POP
- 1000G_EUR
- 1000G_AFR
- 1000G_EAS

The only difference is the sample (.fam) and corresponding genotypes(.bed). The SNP lists, I mean those .bim files are exactly the same. I did not remove SNPs that are A/T, G/C. There are INDELs as well. But it looks like your code would discard those SNPs either in your QC step or later when matching SUMSTAT and LDREF SNPs. But anyway, I tested the 4 LDREF sets with exactly the same SNPs.

I was able to successfully run FUSION.assoc_test.R using 1000G_ALL_POP and 1000G_EUR without any warnings. Roughly 40 out of 72 were skipped for 1000G_AFR. And 72/72 were skipped for 1000G_EAS.

I looked into your codes, which I think are totally great. By adding some simple debugging codes around your LD imputation blocks (where you computed cur.wgt, cur.impz), I came to notice that the warnings I got may be due to significant genotype differences among major populations around specific loci.

I will continue working on making TWAS work using self-generated LDREF, either by trying a different gwas sumstat, or using additional reference panels, or else. If you have any suggestions or hints, I would be really grateful for that.

Thank you!
Hu

**Comment by sureyana956** [comment]
The reason why I got this error is simply because the R function scale() would output NA if the input values are identical. So if the genotypes of a SNP for all samples are exactly the same, for example rs5992999 in EAS, then we would get NAs which caused the gene (wgt file) to be skipped later. To avoid such unexpected behavior, it's better to increase the sample size of the reference panel to diversity the genotypes. If that's not feasible, we may remove NAs after scale(). But do you think if it safe to do that? 

BTW, I am now able to get similar results for EAS as your EUR examples, though the gene statistics differ to some extend, which is totally expected.

**Comment by sashagusev** [comment]
Hi Hu, thanks for looking into this some more. The code for constructing weights has a check for monomorphic SNPs:

https://github.com/gusevlab/fusion_twas/blob/3cff026cffc34a74c1f97e2c63e0ea01adf581d9/FUSION.compute_weights.R#L260

It sounds like we need to put in a similar check & warning when running the FUSION.assoc_test.R so that NA's don't creep into the analysis. Does that make sense?

One quick way to avoid this would be to set a minor allele frequency cutoff in plink so that any non-polymorphic SNPs are removed. I don't think you necessarily need to increase the reference size (though that would help) as it is expected that a handful of SNPs will be monomorphic in non-Europeans and should be set to zero.

Lastly, keep in mind that using weights built in one population to predict into another population can have unstable behavior if the LD differs substantially between populations. In general you want the weights, LDREF, and GWAS to be from the same population. But if that's not possible, you want the LDREF and GWAS to be from the same population to avoid false-positives.

**Comment by sureyana956** [comment]
Great! Good to know that you've already implemented a step to check for monomorphic SNPs. I did a very much similar thing in the FUSION.assoc_test.R in my local computer. So you may probably want to release a future version that tackles with potential monomorphic SNPs in FUSION.assoc_test.R as well. You know, you FUSION/TWAS is getting more popular now.

Per your second point, I totally agree with you. The fact is, I am trying to compare a specific cancer type among different populations using population-specific GWAS. So I need different reference sets. Thank you for pointing that out.

**Comment by sashagusev** [comment]
Great, I'll put in an error check!
