### ISSUE TITLE
Training Weights Error

### ISSUE THREAD

**Issue by jgockley62** [gusevlab/fusion_twas#8]
Hi, 

I'm trying to train weights and I'm getting an error on a few genes.
The error seems to happen after using LASSO regression
``` 
tmp/1_148/<FILENAME>.cv.LASSO
Error in reg$coef[2, 4] : subscript out of bounds
Execution halted
```

**Comment by jgockley62** [comment]
Fixed with Adding in if&else depending on the if the value of reg$coef[2, 4] exists

**Comment by sashagusev** [comment]
Hi Jake, this is an odd bug, do you know why the regression was not producing a coefficient?

**Comment by jgockley62** [comment]
The second row of the ```reg$coef``` matrix was all NAs and wasn't assigning a value for that given algorithm. I believe it was usually the elastic net training that forced all the weights to zero that caused this. I ended up changing the following code on line 335 **from**:
```
for ( mod in 1:M ) {
	reg = summary(lm( cv.all[,3] ~ cv.calls[,mod] ))
	cv.performance[ 1, mod ] = reg$adj.r.sq
	cv.performance[ 2, mod ] = reg$coef[2,4]
}
```
**to**
```
# compute rsq + P-value for each model
for ( mod in 1:M ) {
	reg = summary(lm( cv.all[,3] ~ cv.calls[,mod] ))
	cv.performance[ 1, mod ] = reg$adj.r.sq
	if( exists( "reg$coef[2,4]" ) == T ){
		cv.performance[ 2, mod ] = reg$coef[2,4]
	else{
		cv.performance[ 2, mod ] = NA
	}
}
```

**Comment by sashagusev** [comment]
Got it, thank you!

**Comment by jgockley62** [comment]
Quick Fix Gotta remove the quotes otherwise you're going have all NA's...:
```
# compute rsq + P-value for each model
for ( mod in 1:M ) {
	reg = summary(lm( cv.all[,3] ~ cv.calls[,mod] ))
	cv.performance[ 1, mod ] = reg$adj.r.sq
	if( exists( reg$coef[2,4] ) == T ){
		cv.performance[ 2, mod ] = reg$coef[2,4]
	else{
		cv.performance[ 2, mod ] = NA
	}
}
```
