### ISSUE TITLE
Imputing Individual Sample Expression Values

### ISSUE THREAD

**Issue by jgockley62** [gusevlab/fusion_twas#9]
I was wondering what the best way to export imputed gene expression values for each genotype into a matrix to analyze. Is that something I can change ```FUSION.assoc_test.R``` to do this?

**Comment by sashagusev** [comment]
Can you clarify what kind of output you're looking for? Each of the weight files can be loaded in R and contains a matrix of expression weights. You can also use the make_score function (https://github.com/gusevlab/fusion_twas/blob/master/utils/make_score.R) to produce predictor scores that can be loaded with the `plink --score` function to do individual-level prediction/imputation.

**Comment by jgockley62** [comment]
Cool I can use the make score on a gene by gene case and combine post-run. But I was also wondering don't some of the models use intercept values that don't seem to be used used by ```plink --score``` ?

**Comment by sashagusev** [comment]
Yes, you can make_score on all the genes, predict each into your data, and then analyse together in multi-variate model. The models always remove the intercept (i.e. center the phenotype and genotype) so that information does not get used.
